from .buffer_protection import BufferProtection
from .privileges_protecion import PrivilegesProteccion
from .canonization_protection import CanonizationProtection
from .xss_protection import XSSProtection